/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vehiclesalesmanagement;

import com.placeholder.PlaceHolder;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author it17153232 
 */
public class Brand extends javax.swing.JFrame {

    PlaceHolder holder1,holder2;
    /**
     * Creates new form Brand
     */
    public Brand() {
        initComponents();
        comboDeleteReder();
        holder1 = new PlaceHolder(jTextField1, "Enter new Brand");
        holder2 = new PlaceHolder(jTextField2, "Enter Update Name");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 240, 60));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("    Add Brand");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, 150, 60));

        jButton2.setText("Remove Brand");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, 150, 60));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Brand" }));
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 240, 60));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Update Brand Name" }));
        jPanel1.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 240, 60));

        jButton3.setText("Update Brand");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, 150, 120));
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 240, 60));

        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 420, 80));

        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 420, 80));

        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 420, 140));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Brand Manager");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 140, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {

            ResultSet rs = Database.getData("SELECT * FROM brand WHERE brand.Brand_name = '" + jTextField1.getText() + "'");

            if (rs.next()) {
                JOptionPane.showMessageDialog(null, "This Brand already  in the System!");
            } else if(jTextField1.getText().equalsIgnoreCase("")){
            JOptionPane.showMessageDialog(null, "Please Fil the Brand Name!");
            
            }else{
                

                Database.setData("insert into Brand values('0','" + jTextField1.getText() + "')");
                JOptionPane.showMessageDialog(null, "Brand Successfully Added To System");
                jTextField1.setText(null);
                comboRefesher();

                comboDeleteReder();
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        if (jComboBox1.getSelectedItem().toString().equalsIgnoreCase("Select Brand")) {
            JOptionPane.showMessageDialog(null, "plase select brand!");
        } else {

            //===============confirm dialog box=====================
            int response = JOptionPane.showConfirmDialog(null, "Do you Need Delete This Brand and All of this brand records!", "Confirm", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

            if (response == JOptionPane.YES_OPTION) {

                try {
                    ResultSet brand_rs = Database.getData("SELECT *  FROM vehicle WHERE vehicle.brand = '" + jComboBox1.getSelectedItem() + "'");
                    if(brand_rs.next()){
                    
                    ResultSet brand_rs1 = Database.getData("SELECT *  FROM vehicle WHERE vehicle.brand = '" + jComboBox1.getSelectedItem() + "'");
                        
                        while (brand_rs1.next()) {
                            
                           String model = brand_rs1.getString(4);
                           
                           ResultSet captype_rs = Database.getData("SELECT model.engCap,model.type FROM model WHERE model.model='"+model+"'");
                           
                           if(captype_rs.next()){
                           
                               
                                Database.setData("insert into removevehi(status,brand,modelYear,model,engNum,engCap,mileage,chassisNum,sPrice,vImage,discription,type,regNum,vBoolImg,cost_price) values('Delete','" + brand_rs1.getString(2) + "','" + brand_rs1.getString(3) + "','" + model + "','" + brand_rs1.getString(5) + "','" + captype_rs.getString(1) + "','" + brand_rs1.getString(6) + "','" + brand_rs1.getString(7) + "','" + brand_rs1.getString(8) + "','" + brand_rs1.getString(9) + "','" + brand_rs1.getString(10) + "','" + captype_rs.getString(2) + "','" + brand_rs1.getString(11) + "','"+brand_rs1.getString(12)+"','" + brand_rs1.getString(15) + "')");
                           }
                           
                        }
                        
                        
                        Database.setData("DELETE  FROM vehicle WHERE vehicle.brand = '" + jComboBox1.getSelectedItem() + "'");
                    

                    comboRefesher();

                    comboDeleteReder();
                    }
                    
                    Database.setData("DELETE  FROM model WHERE model.bid=(SELECT brand.bid FROM brand WHERE brand.Brand_name  = '" + jComboBox1.getSelectedItem() + "' )");
                    Database.setData("DELETE  FROM  brand WHERE  brand.Brand_name = '" + jComboBox1.getSelectedItem() + "'");

                    JOptionPane.showMessageDialog(null, "Brand had been deleted!");
                    
                    comboRefesher();

                    comboDeleteReder();
                    
                    
                } catch (Exception e) {
                    e.printStackTrace();
                }

            } else if (response == JOptionPane.NO_OPTION) {

            } else if (response == JOptionPane.CLOSED_OPTION) {

            }
        }


    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       if(jComboBox2.getSelectedItem().toString().equalsIgnoreCase("Select Update Brand Name")){
       
       }else{
       
           try {
            
            ResultSet rs = Database.getData("SELECT * FROM vehicle WHERE vehicle.brand = '"+jComboBox2.getSelectedItem()+"' ");
            
            while(rs.next()){
                Database.setData("UPDATE vehicle SET vehicle.brand ='"+jTextField2.getText()+"'  WHERE vehicle.v_id ='"+rs.getString(1)+"' ");
                
            }
            
                    

                    
                    
                    
                    Database.setData("UPDATE brand SET brand.Brand_name='"+jTextField2.getText()+"' WHERE brand.Brand_name= '"+jComboBox2.getSelectedItem()+"'");
                   
                    comboRefesher();

                    comboDeleteReder();
                    JOptionPane.showMessageDialog(null, "Updated!");
                    jTextField2.setText("");
                    
                    
                    
                    
        } catch (Exception e) {
            e.printStackTrace();
        }
       }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Brand.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Brand.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Brand.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Brand.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Brand().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables

    private void comboDeleteReder() {

        try {
            ResultSet rs = Database.getData("select Brand_name from Brand");
            while (rs.next()) {
                jComboBox1.addItem(rs.getString("Brand_name"));
                jComboBox2.addItem(rs.getString("Brand_name"));
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void comboRefesher() {
        jComboBox1.removeAllItems();
        jComboBox1.addItem("Select Brand");
        
        jComboBox2.removeAllItems();
        jComboBox2.addItem("Select Update Brand Name");
        

    }
}
