/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vehiclesalesmanagement;

import com.mysql.jdbc.MysqlDataTruncation;
import java.awt.Image;
import java.io.File;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.Vector;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import net.sf.jasperreports.engine.JREmptyDataSource;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperPrintManager;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;
import static vehiclesalesmanagement.Registerd_Vehicle.path;

/**
 *
 * @author it17153232
 */
public class Exchange_vehicle extends javax.swing.JPanel {

    /**
     * Creates new form Exchange_vehicle
     */
    public Exchange_vehicle() {
        initComponents();
        brandload();
        typeload();
        statusload();
        customerload();
        registerdCount();
        unregisterdcount();
        exchangecount();
        jProgressBar1.setVisible(false);
    }
    static String path2 = "";

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jToggleButton1 = new javax.swing.JToggleButton();
        REGISTERD = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jLabel66 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel60 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jComboBox5 = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel34 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel36 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel38 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        jTextField14 = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        jTextField15 = new javax.swing.JTextField();
        jLabel44 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel45 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<>();
        jLabel46 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel47 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jProgressBar1 = new javax.swing.JProgressBar();
        jPanel5 = new javax.swing.JPanel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 255, 255), null));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jToggleButton1.setBackground(new java.awt.Color(255, 102, 102));
        jToggleButton1.setText("UNREGISTERD");
        jPanel1.add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 120, -1));

        REGISTERD.setBackground(new java.awt.Color(255, 204, 0));
        REGISTERD.setText("REGISTERD");
        REGISTERD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                REGISTERDActionPerformed(evt);
            }
        });
        jPanel1.add(REGISTERD, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 110, -1));

        jToggleButton2.setBackground(new java.awt.Color(102, 255, 102));
        jToggleButton2.setText("EXCHANGE");
        jPanel1.add(jToggleButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, 110, -1));

        jLabel66.setBackground(new java.awt.Color(102, 204, 0));
        jLabel66.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(jLabel66, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, 90, 40));

        jLabel64.setBackground(new java.awt.Color(255, 204, 204));
        jLabel64.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(jLabel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 90, 40));

        jLabel65.setBackground(new java.awt.Color(204, 204, 0));
        jLabel65.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(jLabel65, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 100, 40));

        jLabel61.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 110, 80));

        jLabel63.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jLabel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, 110, 80));

        jLabel62.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jLabel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 120, 80));

        jLabel59.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 340, 80));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText(" Engine Number");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 28, 100, 30));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 28, 169, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText(" Register Number");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 69, 100, 30));
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 69, 169, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("  Chassis Number");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 110, 110, 30));
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 169, 30));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/magnifier-left.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 28, 51, 30));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/magnifier-left.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 69, 51, 30));

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/magnifier-left.png"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 110, 51, 30));

        jLabel60.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 340, 140));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 0, 360, 240));

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 204, 255), null));

        jLabel6.setText("NIC Number");

        jLabel7.setText("Customer name");

        jLabel8.setText("Phone Number");

        jLabel9.setText("Book of Registration");

        jLabel10.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/monitor-sidebar.png"))); // NOI18N
        jButton1.setText("Upload");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Customer" }));
        jComboBox5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox5MouseClicked(evt);
            }
        });
        jComboBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jTextField8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                    .addComponent(jTextField7, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox5, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField7, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField8, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addGap(0, 6, Short.MAX_VALUE))
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(381, 0, 300, 240));

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 204, 204), null));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setText("Brand");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 40, 67, 30));

        jLabel12.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 40, 136, 30));

        jLabel13.setText("Model Year");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 81, 76, 30));

        jLabel14.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 81, 136, 30));

        jLabel15.setText("Model");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 126, 76, 30));

        jLabel16.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 126, 136, 30));

        jLabel17.setText("Engine (CC)");
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 162, -1, 30));

        jLabel18.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 162, 136, 30));

        jLabel19.setText("Mileage  (Km)");
        jPanel3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 203, 80, 30));

        jLabel20.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 203, 136, 30));

        jLabel21.setText("Chassis Number");
        jPanel3.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 244, 80, 30));

        jLabel22.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 244, 136, 30));

        jLabel23.setText("Register Number");
        jPanel3.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(248, 40, -1, 30));

        jLabel24.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(334, 40, 140, 30));

        jLabel25.setText("Engine Number");
        jPanel3.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(248, 81, 80, 30));

        jLabel26.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(334, 81, 140, 30));

        jLabel27.setText("Selling Price(Rs)");
        jPanel3.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(248, 126, 80, 30));

        jLabel28.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(334, 126, 140, 30));

        jLabel29.setText("Type");
        jPanel3.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(248, 162, 80, 30));

        jLabel30.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(334, 162, 140, 30));

        jLabel31.setText("Status");
        jPanel3.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(248, 203, 80, 30));

        jLabel32.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(334, 203, 140, 30));

        jLabel33.setText("Discription");
        jPanel3.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(248, 244, 90, 30));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 288, 180, 150));

        jLabel34.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 288, 270, 150));

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 249, 490, 450));

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 204, 204), null));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel35.setText("Brand");
        jPanel4.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 38, 90, 30));

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel4.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 38, 150, 30));

        jLabel36.setText("Model Year");
        jPanel4.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 79, 100, 30));
        jPanel4.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 79, 150, 30));

        jLabel37.setText("Model");
        jPanel4.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 120, 100, 30));

        jPanel4.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 120, 150, 30));

        jLabel38.setText("Engine(CC)");
        jPanel4.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 161, 110, 30));
        jPanel4.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 161, 150, 30));

        jLabel39.setText("Mileage  (Km)");
        jPanel4.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 202, 90, 30));

        jLabel40.setText("Chassis Number");
        jPanel4.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 243, 110, 30));

        jTextField11.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField11KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField11KeyTyped(evt);
            }
        });
        jPanel4.add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 202, 150, 30));
        jPanel4.add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 243, 150, 30));

        jLabel41.setText(" Register Number");
        jPanel4.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 40, 100, 30));
        jPanel4.add(jTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 40, 160, 30));

        jLabel42.setText("Engine Number");
        jPanel4.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, 100, 30));
        jPanel4.add(jTextField14, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 80, 160, 30));

        jLabel43.setText("Selling Price  (Rs)");
        jPanel4.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, 100, 30));
        jPanel4.add(jTextField15, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 120, 160, 30));

        jLabel44.setText("Type");
        jPanel4.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, 90, 30));

        jPanel4.add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, 160, 30));

        jLabel45.setText("Status");
        jPanel4.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 200, 90, 30));

        jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4ActionPerformed(evt);
            }
        });
        jPanel4.add(jComboBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 200, 160, 30));

        jLabel46.setText("Discription");
        jPanel4.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 240, 90, 30));

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        jPanel4.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 240, 160, 130));

        jLabel47.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 250, 136));

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/monitor-sidebar.png"))); // NOI18N
        jButton2.setText("Upload");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 110, 40));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Sync.png"))); // NOI18N
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 380, 30, 40));

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton3.setText("   Convert Info");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 380, 160, 45));
        jPanel4.add(jProgressBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 414, 250, -1));

        add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(511, 249, 610, 450));

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 102, 102), null));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel49.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel49.setText("Mileage (Km) Difference");
        jPanel5.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 13, 170, 30));

        jLabel50.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel50.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel5.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 49, 93, 33));

        jLabel51.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel51.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel5.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(318, 49, 100, 33));

        jLabel52.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel52.setForeground(new java.awt.Color(204, 204, 0));
        jLabel52.setText("        System");
        jPanel5.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 88, 93, -1));

        jLabel53.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel53.setForeground(new java.awt.Color(255, 51, 51));
        jLabel53.setText("Exchange");
        jPanel5.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 88, 76, -1));

        jLabel54.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel54.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel5.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 13, 203, 30));

        jLabel55.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel55.setText(" Model Year Difference ");
        jPanel5.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 49, 190, 33));

        jLabel56.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel56.setText(" Balance (Rs)");
        jPanel5.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 109, 190, 43));

        jLabel57.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel57.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel5.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 109, 203, 43));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/if_file_documents-16_854147.png"))); // NOI18N
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 172, 40, 40));

        jLabel58.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/printer_add.png"))); // NOI18N
        jPanel5.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, 40, 30));

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton7.setText("    Approve Exchange");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 169, 47));

        jButton8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton8.setText("        Print Report");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, 170, 47));

        add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 0, 430, 240));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JFileChooser f = new JFileChooser();
        f.setCurrentDirectory(new File(System.getProperty("user.home")));
        FileNameExtensionFilter fil = new FileNameExtensionFilter("*.IMAGE", "jpeg");
        f.addChoosableFileFilter(fil);
        int r = f.showSaveDialog(null);
        if (r == f.APPROVE_OPTION) {
            File file = f.getSelectedFile();
            path2 = file.getAbsolutePath();

            new Thread(new Runnable() {
                @Override
                public void run() {
                    for (int i = 0; i <= 50; i++) {
                        // jProgressBar1.setValue(i);
                        // jProgressBar1.setVisible(true);

                        try {
                            Thread.sleep(20);
                        } catch (Exception e) {
                            e.printStackTrace();
                        }
                    }
                    jLabel10.setIcon(new ImageIcon(new ImageIcon(path2).getImage().getScaledInstance(jLabel10.getWidth(), jLabel10.getHeight(), Image.SCALE_SMOOTH)));
                    //jProgressBar1.setVisible(false);
                }
            }).start();

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        JFileChooser f = new JFileChooser();
        f.setCurrentDirectory(new File(System.getProperty("user.home")));
        FileNameExtensionFilter fil = new FileNameExtensionFilter("*.IMAGE", "jpeg");
        f.addChoosableFileFilter(fil);
        int r = f.showSaveDialog(null);
        if (r == f.APPROVE_OPTION) {
            File file = f.getSelectedFile();
            path = file.getAbsolutePath();

            new Thread(new Runnable() {
                @Override
                public void run() {
                    for (int i = 0; i <= 100; i++) {
                        jProgressBar1.setValue(i);
                        jProgressBar1.setVisible(true);

                        try {
                            Thread.sleep(20);
                        } catch (Exception e) {
                            e.printStackTrace();
                        }
                    }
                    jLabel47.setIcon(new ImageIcon(new ImageIcon(path).getImage().getScaledInstance(jLabel47.getWidth(), jLabel47.getHeight(), Image.SCALE_SMOOTH)));
                    jProgressBar1.setVisible(false);
                }
            }).start();

        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        try {
            int result = Integer.valueOf(jLabel20.getText()) - Integer.valueOf(jTextField11.getText());
            jLabel54.setText(Double.toString(result));

        } catch (java.lang.NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Please Fill the exchange Vehicle Details");

        } catch (Exception e) {

        }

        try {
            int result = Integer.valueOf(jLabel28.getText()) - Integer.valueOf(jTextField15.getText());
            jLabel57.setText(Double.toString(result));

        } catch (java.lang.NumberFormatException ex) {
            //JOptionPane.showMessageDialog(null, "Please Enter Only Price");

        } catch (Exception e) {

        }

        jLabel50.setText(jLabel14.getText());
        jLabel51.setText(jTextField9.getText());


    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased

    }//GEN-LAST:event_jTextField1KeyReleased
    String imgp;
    String engNumber;

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        engNumber = jTextField1.getText();
        long count = 0;

        try {
            ResultSet rs = Database.getData("SELECT * FROM vehicle WHERE engNum= '" + engNumber + "'");

            if (engNumber.isEmpty()) {
                JOptionPane.showMessageDialog(null, "please fill the engine number");
            } else {

                while (rs.next()) {
                    //System.out.println("Testing Sucess");
                    jLabel12.setText(rs.getString(2));
                    jLabel14.setText(rs.getString(3));
                    jLabel16.setText(rs.getString(4));
                    jLabel18.setText(rs.getString(6));
                    jLabel20.setText(rs.getString(7));
                    jLabel22.setText(rs.getString(8));
                    jLabel24.setText(rs.getString(13));
                    jLabel26.setText(rs.getString(5));
                    jLabel28.setText(rs.getString(9));
                    jLabel30.setText(rs.getString(12));
                    jLabel32.setText(rs.getString(16));
                    jTextArea1.setText(rs.getString(11));

                    String n = rs.getString(10);
                    String x = n.replace('/', '\\');
                    imgp = x;

                    if (new File(n).exists()) {
                        jLabel34.setIcon(new ImageIcon(new ImageIcon(x).getImage().getScaledInstance(jLabel34.getWidth(), jLabel34.getHeight(), Image.SCALE_SMOOTH)));
                    } else {
                        JOptionPane.showMessageDialog(null, "Image not Found Please Insert New Image Or Update Image");
                    }

                    count = 1;

                }

                if (count == 1) {

                } else {
                    JOptionPane.showMessageDialog(null, "Data not found");

                }

            }

        } catch (Exception e) {
            e.printStackTrace();
        }


    }//GEN-LAST:event_jButton4ActionPerformed
    String r_number;
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        r_number = jTextField2.getText();
        int count = 0;

        try {
            ResultSet rs = Database.getData("SELECT * FROM vehicle WHERE regNum= '" + r_number + "'");

            if (r_number.isEmpty()) {
                JOptionPane.showMessageDialog(null, "please fill the Register  number");
            } else {

                while (rs.next()) {
                    //System.out.println("Testing Sucess");
                    jLabel12.setText(rs.getString(2));
                    jLabel14.setText(rs.getString(3));
                    jLabel16.setText(rs.getString(4));
                    jLabel18.setText(rs.getString(6));
                    jLabel20.setText(rs.getString(7));
                    jLabel22.setText(rs.getString(8));
                    jLabel24.setText(rs.getString(13));
                    jLabel26.setText(rs.getString(5));
                    jLabel28.setText(rs.getString(9));
                    jLabel30.setText(rs.getString(12));
                    jLabel32.setText(rs.getString(16));
                    jTextArea1.setText(rs.getString(11));

                    String n = rs.getString(10);
                    String x = n.replace('/', '\\');
                    imgp = x;

                    if (new File(n).exists()) {
                        jLabel34.setIcon(new ImageIcon(new ImageIcon(x).getImage().getScaledInstance(jLabel34.getWidth(), jLabel34.getHeight(), Image.SCALE_SMOOTH)));
                    } else {
                        JOptionPane.showMessageDialog(null, "Image not Found Please Insert New Image Or Update Image");
                    }

                    count = 1;

                }

                if (count == 1) {

                } else {
                    JOptionPane.showMessageDialog(null, "Data not found");

                }

            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton5ActionPerformed
    String c_number;
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed

        c_number = jTextField3.getText();

        int count = 0;

        try {
            ResultSet rs = Database.getData("SELECT * FROM vehicle WHERE chassisNum= '" + c_number + "'");

            if (c_number.isEmpty()) {
                JOptionPane.showMessageDialog(null, "please fill the Chassis  number");
            } else {

                while (rs.next()) {
                    //System.out.println("Testing Sucess");
                    jLabel12.setText(rs.getString(2));
                    jLabel14.setText(rs.getString(3));
                    jLabel16.setText(rs.getString(4));
                    jLabel18.setText(rs.getString(6));
                    jLabel20.setText(rs.getString(7));
                    jLabel22.setText(rs.getString(8));
                    jLabel24.setText(rs.getString(13));
                    jLabel26.setText(rs.getString(5));
                    jLabel28.setText(rs.getString(9));
                    jLabel30.setText(rs.getString(12));
                    jLabel32.setText(rs.getString(16));
                    jTextArea1.setText(rs.getString(11));

                    String n = rs.getString(10);
                    String x = n.replace('/', '\\');
                    imgp = x;

                    if (new File(n).exists()) {
                        jLabel34.setIcon(new ImageIcon(new ImageIcon(x).getImage().getScaledInstance(jLabel34.getWidth(), jLabel34.getHeight(), Image.SCALE_SMOOTH)));
                    } else {
                        JOptionPane.showMessageDialog(null, "Image not Found Please Insert New Image Or Update Image");
                    }

                    count = 1;

                }

                if (count == 1) {

                } else {
                    JOptionPane.showMessageDialog(null, "Data not found");

                }

            }

        } catch (Exception e) {
            e.printStackTrace();
        }


    }//GEN-LAST:event_jButton6ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        jComboBox2.removeAllItems();
        String s = null;
        try {

            ResultSet rs1 = Database.getData("select bid from brand where Brand_name='" + jComboBox1.getSelectedItem() + "'");

            //System.out.println(s);
            if (rs1.next()) {

                s = rs1.getString("bid");
                //System.out.println(s);

            }

            ResultSet rs = Database.getData("select m.model from brand b,model m where m.bid='" + s + "' group by m.bid,m.model");

            while (rs.next()) {

                jComboBox2.addItem(rs.getString("m.model"));

            }

        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTextField11KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField11KeyReleased


    }//GEN-LAST:event_jTextField11KeyReleased

    private void jTextField11KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField11KeyTyped

    }//GEN-LAST:event_jTextField11KeyTyped

    private void jComboBox5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox5MouseClicked


    }//GEN-LAST:event_jComboBox5MouseClicked

    private void jComboBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox5ActionPerformed
        try {
            ResultSet rs = Database.getData("select * from customer where NIC='" + jComboBox5.getSelectedItem() + "'");
            if (rs.next()) {

                jTextField7.setText(rs.getString(5));
                jTextField8.setText(rs.getString(3));

            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jComboBox5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed

        if (jLabel57.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "first convert the info!");

        } else if (jComboBox5.getSelectedItem().toString().equalsIgnoreCase("Select Customer")) {
            JOptionPane.showMessageDialog(null, "first select the NIC!");

        } else {

            //exchange vehicle
            String vBookImg = "null";
            String vimag = "null";
            String vid = "null";
            String t = new SimpleDateFormat("MMM dd, yyyy").format(new Date());
            String rpnew = path2.replace('\\', '/');
            String rp = path.replace('\\', '/');
            String cid = "null";

            try {

                Database.setData("insert into exchangeveh(eBrand,gBrand,eModel,gModel,exchangeDate,balance,ePrice,gPrice,eType,gType,book_Image) values('" + jComboBox1.getSelectedItem() + "','" + jLabel12.getText() + "','" + jComboBox2.getSelectedItem() + "','" + jLabel16.getText() + "','" + t + "','" + jLabel57.getText() + "','" + jTextField15.getText() + "','" + jLabel28.getText() + "','" + jComboBox3.getSelectedItem() + "','" + jLabel30.getText() + "','" + rpnew + "')");
                JOptionPane.showMessageDialog(null, "Echanged Vehicle Sucess !");
                System.out.println(jLabel28.getText());
            } catch (Exception e) {
                e.printStackTrace();
            }

            // removed vehicle 
            try {

                ResultSet vBook_rs = Database.getData("select * from vehicle where chassisNum='" + jLabel22.getText() + "'");
                if (vBook_rs.next()) {
                    vBookImg = vBook_rs.getString(14);
                    vimag = vBook_rs.getString(10);
                    vid = vBook_rs.getString(1);

                }

            } catch (Exception e) {
                e.printStackTrace();
            }

            try {

                Database.setData("insert into removevehi (status,brand,modelYear,model,engNum,engCap,mileage,chassisNum,sPrice,vImage,discription,type,regNum,vBoolImg) values ('Exchange','" + jLabel12.getText() + "','" + jLabel14.getText() + "','" + jLabel16.getText() + "','" + jLabel26.getText() + "','" + jLabel18.getText() + "','" + jLabel20.getText() + "','" + jLabel22.getText() + "','" + jLabel28.getText() + "','" + vimag + "','" + jTextArea1.getText() + "','" + jLabel30.getText() + "','" + jLabel24.getText() + "','" + vBookImg + "')");
                Database.setData("delete  from vehicle where v_id ='" + vid + "' ");
            } catch (Exception e) {
                e.printStackTrace();
            }

            //vehicle inset quary and throws the details to removedveh table
            try {
                ResultSet cid_rs = Database.getData("select * from customer where NIC  ='" + jComboBox5.getSelectedItem() + "' ");

                if (cid_rs.next()) {
                    cid = cid_rs.getString(1);
                }
            } catch (Exception e) {
            }

            // insert values for vehicle table from exchange vehicle
            try {

                Database.setData("insert into vehicle(brand,modelYear,model,engNum,engCap,mileage,chassisNum,sPrice,vImage,discription,type,regNum,vBoolImg,c_id,status) values('" + jComboBox1.getSelectedItem() + "','" + jTextField9.getText() + "','" + jComboBox2.getSelectedItem() + "','" + jTextField14.getText() + "','" + jTextField10.getText() + "','" + jTextField11.getText() + "','" + jTextField12.getText() + "','" + jTextField15.getText() + "','" + rp + "','" + jTextArea2.getText() + "','" + jComboBox3.getSelectedItem() + "','" + jTextField13.getText() + "','" + rpnew + "','" + cid + "','" + jComboBox4.getSelectedItem() + "')");
                JOptionPane.showMessageDialog(null, "Exchanging Success !");
            } catch (Exception e) {
                e.printStackTrace();
            }
        }

    }//GEN-LAST:event_jButton7ActionPerformed

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
        if (jComboBox4.getSelectedItem().equals("Unregisterd")) {
            jTextField13.setText("Null");
            jTextField13.setEnabled(false);

        } else {
            jTextField13.setEnabled(true);

        }
    }//GEN-LAST:event_jComboBox4ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // String path1 =" ‪F:\\Diploma Level -1\\SAD\\Viva Project\\Reports\\Exchanging Vehicles.jrxml";
        String path1 = "C:\\Users\\it17153232\\Desktop\\Vehicle Sale Project\\Project\\VehicleSalesManagement\\src\\Reports\\ExchangingReport.jrxml";
        try {
            Map parms = new HashMap();
            parms.put("b", jLabel12.getText());
            parms.put("my", jLabel14.getText());
            parms.put("mo", jLabel16.getText());
            parms.put("engC", jLabel18.getText());
            parms.put("milea", jLabel20.getText());
            parms.put("price", jLabel28.getText());
            parms.put("type", jLabel30.getText());
            parms.put("status", jLabel32.getText());

            parms.put("eBrand", jComboBox1.getSelectedItem());
            parms.put("eModelYear", jTextField9.getText());
            parms.put("eModel", jComboBox2.getSelectedItem());
            parms.put("eEngC", jTextField10.getText());
            parms.put("eMileage", jTextField11.getText());
            parms.put("ePrice", jTextField15.getText());
            parms.put("eType", jComboBox3.getSelectedItem());
            parms.put("eStatus", jComboBox4.getSelectedItem());

            parms.put("img", imgp);
            parms.put("img2", path);

            parms.put("sp", jLabel28.getText());
            parms.put("ep", jTextField15.getText());
          
            
             parms.put("minb", jLabel57.getText());
            
            
           

            if (Double.valueOf(jLabel57.getText()) < 0) {

                parms.put("des","You have want to pay"+jLabel57.getText());

            } else if (Double.valueOf(jLabel57.getText()) == 0) {

                parms.put("des", "Customer have want to pay"+jLabel57.getText());
               
                

            }else{
                parms.put("des", "Exchange only");
            
            }
            
            
            
            
            

            JREmptyDataSource dataSource = new JREmptyDataSource();
            JasperReport jr = JasperCompileManager.compileReport(path1);
            JasperPrint jasperPrint = JasperFillManager.fillReport(jr, parms, dataSource);//set 2nd param map
            JasperViewer.viewReport(jasperPrint, false);
            //JasperPrintManager.printReport(jasperPrint, true);

        } catch (JRException ex) {
            ex.printStackTrace();
        }


    }//GEN-LAST:event_jButton8ActionPerformed

    private void REGISTERDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_REGISTERDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_REGISTERDActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton REGISTERD;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    // End of variables declaration//GEN-END:variables

    private void brandload() {

        try {
            ResultSet rs = Database.getData("select Brand_name from Brand");
            while (rs.next()) {
                jComboBox1.addItem(rs.getString("Brand_name"));

            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void typeload() {
        jComboBox3.addItem("Car");
        jComboBox3.addItem("Van");
        jComboBox3.addItem("Bus");
        jComboBox3.addItem("Truck");
        jComboBox3.addItem("Lorry");
        jComboBox3.addItem("Jeep");
    }

    private void statusload() {
        jComboBox4.addItem("Registerd");
        jComboBox4.addItem("Unregisterd");

    }

    private void customerload() {
        try {

            ResultSet rs = Database.getData("select * from customer");
            while (rs.next()) {

                jComboBox5.addItem(rs.getString("NIC"));

            }

        } catch (Exception e) {
        }
    }

    private void registerdCount() {
        try {
            ResultSet rs = Database.getData("select count(*)as reg from vehicle where status='Registerd'");
            while (rs.next()) {
                jLabel64.setText(Integer.toString(rs.getInt("reg")));

            }

        } catch (Exception e) {
        }
    }

    private void unregisterdcount() {
        try {
            ResultSet rs = Database.getData("select count(*)as reg from vehicle where status='Unregistered'");
            while (rs.next()) {
                jLabel65.setText(Integer.toString(rs.getInt("reg")));

            }

        } catch (Exception e) {
        }

    }

    private void exchangecount() {
        try {
            ResultSet rs = Database.getData("select count(*)as reg from exchangeveh");
            while (rs.next()) {
                jLabel66.setText(Integer.toString(rs.getInt("reg")));

            }

        } catch (Exception e) {
        }
    }
}
